name: Checks

on:
  workflow_call:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        show-progress: false
    - name: Setup Node.js
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version-file: .nvmrc
        check-latest: true
    - name: Enable Corepack + pin Yarn
      run: |
        corepack enable
        # Optional but explicit; Corepack will also read package.json:packageManager
        corepack prepare yarn --activate
        yarn --version
    - name: Cache Yarn artifacts
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install Dependencies
      run: yarn install --immutable
    - name: Run Check Types
      run: yarn run check:types
    - name: JSR check
      run: yarn dlx jsr publish --dry-run
