name: Checks

on:
  workflow_call:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        show-progress: false
    - name: Setup Node.js
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version-file: .nvmrc
        check-latest: true
        cache: yarn
    - name: Install Dependencies
      run: yarn install --immutable
    - name: Run Check Types
      run: yarn run check:types
    # - name: Run Linter
    #   run: yarn run lint
