name: Tag

env:
  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

on:
  push:
    tags:
      - 'v**'

jobs:
  release-package:
    name: Release Package on NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
    - name: Checkout Repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        show-progress: false
    - name: Setup Node.js
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version-file: .nvmrc
        check-latest: true
    - name: Enable Corepack + pin Yarn
      run: |
        corepack enable
        # Optional but explicit; Corepack will also read package.json:packageManager
        corepack prepare yarn --activate
        yarn --version
    - name: Cache Yarn artifacts
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install Dependencies
      run: yarn install --immutable
    - name: Build
      run: yarn build
    - name: Publish to NPM
      run: yarn npm publish
    - name: Publish to JSR
      run: yarn dlx jsr publish
